version: "3.9"

services:
    redis:
        image: "redis:alpine"
        container_name: "${APP_NAME}_REDIS"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - sail-redis:/data
        networks:
            default:
                ipv4_address: 172.30.0.2
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    nginx:
        build:
            context: "./docker/nginx"
            args:
                queueTimeout: 30
                queueTries: 2
                queues: default,indexing,notifications
        container_name: "${APP_NAME}_NGINX"
        depends_on:
            - php-fpm
        volumes:
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        ports:
            - "${NGINX_HOST_HTTPS_PORT}:443"
            - "${NGINX_HOST_HTTP_PORT}:80"
        networks:
            default:
                ipv4_address: 172.30.0.3

    php-fpm:
        build:
            context: "./docker/php-fpm"
        container_name: "${APP_NAME}_PHP_FPM"
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ./docker/php-fpm/laravel.ini:/usr/local/etc/php/conf.d/app.ini
        depends_on:
            - mysql
        logging:
            options:
                max-size: "10k"
        networks:
            default:
                ipv4_address: 172.30.0.4
        ports:
            - "9000:9000"

    mysql:
        container_name: "${APP_NAME}_MYSQL"
        image: mysql:8.0.30-debian
        # image: maurosoft1973/alpine-mariadb
        tty: true
        command: --default-authentication-plugin=mysql_native_password
            --max_connections=666
            --bind-address=0.0.0.0
            --transaction-isolation=READ-COMMITTED
        restart: unless-stopped
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            TIMEZONE: "America/Sao_Paulo"
        volumes:
            - lara-mysql:/var/lib/mysql
            - "./create-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
        networks:
            default:
                ipv4_address: 172.30.0.5
    phpmyadmin:
        container_name: "${APP_NAME}_PHPMYADMIN"
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - 8082:80
        environment:
            PMA_HOSTS: mysql
            PMA_PORT: ${FORWARD_DB_PORT:-3306}
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}
            PMA_ARBITRARY: 1
            UPLOAD_LIMIT: 350M
        depends_on:
            - mysql
        networks:
            default:
                ipv4_address: 172.30.0.6

networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.30.0.0/24

volumes:
    sail-redis:
        driver: local
    lara-mysql:
        driver: local
